---
title: "Cyclistic Bike-Sharing Data Analysis"
author: "Thanakorn Thanakraikiti"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    css: "style.css"
    theme: paper
    df_print: paged
    number_sections: true
    # toc: true
    # toc_depth: 2
    # toc_float:
    #   collapsed: false
    #   smooth_scroll: false
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "/Users/thanakorn.tha/Code/data-analytics/cyclistic-analysis")
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  out.width = "100%",
  fig.align = "center"
)
```

```{r load-packages}
library(tidyverse) # Help import data and wrangle data
library(janitor) # Help clean data
library(ggplot2) # Help visualize the data
theme_set(theme_bw()) # Set theme to theme_bw())
library(ggmap) # Help visualize the map
```

------------------------------------------------------------------------

# Introduction

Cyclistic is a bike-share company in Chicago that launched a successful bike-share offering in 2016. Its marketing strategy primarily focused on building general awareness and appealing to broad consumer segments. Cyclistic offers a variety of pricing plans, including single-ride passes, full-day passes, and annual memberships. Cyclistic classifies its riders into two groups based on these plans: casual riders are those who purchase single-ride passes or full-day passes and annual members are those who purchase an annual membership.

Cyclistic's flexible pricing plans attract more customers, but financial analysts have found that annual members are more profitable. This suggests that a marketing campaign that targets existing customers is likely more effective at expanding revenue than a campaign that targets new customers.

Therefore, Cyclistic's marketing team is interested in understanding how casual riders and annual members use Cyclistic bikes differently. By understanding these differences, the marketing team can develop more targeted marketing strategies to convert casual riders into annual members.

## Business Task

This report will analyze Cyclistic's historical bike trip data from 2022 in order to identify how annual members and casual riders use Cyclistic bikes differently. These insights will be used to develop marketing strategies that appeal to casual riders and encourage them to subscribe to annual memberships.

## Key Stakeholders

Key stakeholders include:

-   Marketing analytics team who collect, analyze, and report data to help guide Cyclistic's marketing strategy
-   Marketing manager who supports the marketing campaign to promote Cyclistic's bike-share program
-   Executive team who approve the recommended marketing program

# Data Sources

This report will use Cyclistic's historical trip data from January 2022 to December 2022 as its primary source. The data can be downloaded from the company's website via [this link](https://divvybikes.com/system-data). It was collected by the City of Chicago (a government agency) and published by Cyclistic. The data contains historical trip data for all of the company's customer (rider) data since 2013, including the following information: ride history, the location of stations for each ride, and other relevant information

## Data Description and Organization

The data is stored in twelve CSV files, one for each month of 2022 (`202201-divvy-tripdata.csv` through `202212-divvy-tripdata.csv`). Each file contains a set of fields (columns) and records (rows). Each record represents a single bike trip, which is uniquely identified by an identifier for the ride.

<!-- Attach picture -->

Every ride contains the following 13 fields:

-   `ride_id` : A unique identifier for the ride
-   `rideable_type` : The type of bike for the ride (classic bike, electric bike or docked bike)
-   `started_at` : The date and time at which the ride started
-   `ended_at` : The date and time at which the ride ended
-   `start_station_id` : The ID of the station where the ride started
-   `start_station_name` : The name of the station where the ride started
-   `end_station_id` : The ID of the station where the ride ended
-   `end_station_name` : The name of the station where the ride ended
-   `start_lat` : The latitude of the station where the ride started
-   `start_lng` : The longitude of the station where the ride started
-   `end_lat` : The latitude of the station where the ride ended
-   `end_lng` : The longitude of the station where the ride ended
-   `member_casual` : The type of user who took the ride (member or casual)

## Data Credibility

The data was evaluated for bias and credibility using the ROCCC method:

-   **Reliable** : The data is considered reliable because it is open data provided by Cyclistic and the City of Chicago. It is a comprehensive and accurate dataset of Cyclistic's historical bike trips. The data includes information on the start and end location of each trip, the time of day the trip was taken, the type of user (casual or annual member), and the length of the trip. There are some missing values in some fields, but these can be used to explore how different customer types use Cyclistic bikes.
-   **Original** : The data is considered to be original, based on a primary source of information from the company.
-   **Comprehensive** : It is important to note that Cyclistic is subject to data privacy restrictions that prohibit the use of riders' personally identifiable information (PII). This means that the company cannot connect pass purchases to credit card numbers to determine if casual riders live in the Cyclistic service area or if they have purchased multiple single passes, as well as identify the rider's gender and age. Despite these restrictions, the data is complete and contains all the information needed to understand how members and casual riders use Cyclistic bikes. This includes information such as the number of rides taken, the length of each ride, the start and end stations of each ride, the time of day each ride was taken.
-   **Current** : The data is current and updated monthly. The selected datasets are the most recent data available.
-   **Cited** : The data is properly cited as it contains the dataset name, author, and published year.

Overall, the Cyclistic bike data is considered a credible source for analysis based on the Reliability, Originality, Comprehensiveness, Currency, and Citation (ROCCC) method. The data can be used to explore how different customer types use Cyclistic bikes. For example, the data can be used to determine which customer segments are most likely to use Cyclistic bikes for commuting, recreation, or transportation. The data can also be used to identify trends in bike usage, such as the time of day when bikes are most likely to be used or the types of bikes that are most popular.

While there are some restrictions on rider's personal information, there is still a great deal of information that can be learned from it. However, the data needs to be processed before analysis can be performed. This includes cleaning the data to remove errors and inconsistencies, and transforming the data into a format that is suitable for analysis. The data processing will be performed in the next section.

# Data Cleaning and Manipulation

This section documents the process of data cleansing and data transformation. This included the following tasks:

-   Removing duplicate records
-   Fixing station name
-   Identifying and correcting missing values
-   Adding new calculated columns
-   Removing outlier values

The R programming language was used in conjunction with the RStudio integrated development environment (IDE) to complete these tasks. Each CSV file was loaded into a separate variable and then combined into the `trip_data_v2` variable, as shown in the table below.

```{r collect-data}
# Read CSV files into separate variables
trip_01 <- read_csv("./data/raw-data/202201-divvy-tripdata.csv")
trip_02 <- read_csv("./data/raw-data/202202-divvy-tripdata.csv")
trip_03 <- read_csv("./data/raw-data/202203-divvy-tripdata.csv")
trip_04 <- read_csv("./data/raw-data/202204-divvy-tripdata.csv")
trip_05 <- read_csv("./data/raw-data/202205-divvy-tripdata.csv")
trip_06 <- read_csv("./data/raw-data/202206-divvy-tripdata.csv")
trip_07 <- read_csv("./data/raw-data/202207-divvy-tripdata.csv")
trip_08 <- read_csv("./data/raw-data/202208-divvy-tripdata.csv")
trip_09 <- read_csv("./data/raw-data/202209-divvy-tripdata.csv")
trip_10 <- read_csv("./data/raw-data/202210-divvy-tripdata.csv")
trip_11 <- read_csv("./data/raw-data/202211-divvy-tripdata.csv")
trip_12 <- read_csv("./data/raw-data/202212-divvy-tripdata.csv")

# Combine month's data frames into a single data frame
trip_data <- bind_rows(
  trip_01, trip_02, trip_03, trip_04, trip_05, trip_06, 
  trip_07, trip_08, trip_09, trip_10, trip_11, trip_12)

# Copy a new data frame but with the rows ordered by 'started_at'
trip_data_v2 <- trip_data[order(trip_data$started_at), ]
```

```{r preview-data}
# Print the first 6 rows of the data to have a quick look at it
head(trip_data_v2)
```

Upon initial inspection, the dataset contains 5,667,717 rows and 13 columns.

## Removing Duplicate Records

The first step in data cleansing is to detect and eliminate duplicate data. Duplicate data refers to rows or cells that contain the same data. It can occur when data is entered incorrectly or when data is merged from multiple sources. Duplicate data can skew the results of analysis, so it is important to eliminate it before proceeding.

The command below is used to count the number of rows and unique rides in the dataset.

```{r count-unique-ride, echo=TRUE}
trip_data_v2 %>% 
  summarize(total_ride = n(), 
            unique_ride = length(unique(trip_data_v2$ride_id)))
```

The result of the command shows that there are a total of 5,667,717 rows and 5,667,717 unique rides in the dataset. This indicates that there are no duplicate values in the dataset.

## Fixing Station Names

The second step in data cleansing is to standardize the data. This involves ensuring that all of the data is in a consistent format, with the same data types and values. This can be a time-consuming process, but it is essential to ensure the accuracy and reliability of the data.

Initially, irrelevant columns were removed as they were not required for this analysis. These columns included `start_station_id` and `end_station_id.`

```{r remove-columns, echo=TRUE}
# Remove 'start_station_id' and 'end_station_id' due to unnecessary for this analysis
trip_data_v2 <- trip_data_v2 %>% 
  select(-c(start_station_id, end_station_id))
```

An inspection of the start and end station columns were examined and revealed some inconsistent formattings. The following test stations were found: `Pawel Bialowas - Test- PBSC charging station`, `Hastings WH 2`, `DIVVY CASSETTE REPAIR MOBILE STATION`, `Base - 2132 W Hubbard Warehouse`, `Base - 2132 W Hubbard`, `NewHastings`, `WestChi`, and `WEST CHI-WATSON`. This can be done by executing the command below:

```{r inspect-stations}
# Examine the starting and ending station names
start_station <- count(trip_data_v2, start_station_name, name = "total_station")
end_station <- count(trip_data_v2, end_station_name, name = "total_station")
```

```{r remove-test-station, echo=TRUE}
# Remove all rows that have eight test stations in both the starting and ending locations
trip_data_v2 <- trip_data_v2[
  !(trip_data_v2$start_station_name %in% c("Pawel Bialowas - Test- PBSC charging station", 
                                           "Hastings WH 2", "DIVVY CASSETTE REPAIR MOBILE STATION", 
                                           "Base - 2132 W Hubbard Warehouse", 
                                           "Base - 2132 W Hubbard", 
                                           "NewHastings", 
                                           "WestChi", 
                                           "WEST CHI-WATSON") | 
   trip_data_v2$end_station_name %in% c("Pawel Bialowas - Test- PBSC charging station", 
                                        "DIVVY CASSETTE REPAIR MOBILE STATION", 
                                        "Base - 2132 W Hubbard Warehouse", 
                                        "Base - 2132 W Hubbard", 
                                        "NewHastings", 
                                        "WestChi", 
                                        "WEST CHI-WATSON")), ]
```

The following extra texts were found in station names: `*`, ` - Charging`, ` (Temp)`, and `amp;`.

```{r remove-unwanted-characters, echo=TRUE}
# Remove all unwanted characters from the starting and ending station names
trip_data_v2 <- trip_data_v2 %>% 
  mutate(start_station_name = str_replace_all(start_station_name, fixed("*"),           "")) %>% 
  mutate(start_station_name = str_replace_all(start_station_name, fixed(" - Charging"), "")) %>% 
  mutate(start_station_name = str_replace_all(start_station_name, fixed(" (Temp)"),     "")) %>% 
  mutate(start_station_name = str_replace_all(start_station_name, fixed("amp;"),        "")) %>% 
  mutate(end_station_name   = str_replace_all(end_station_name,   fixed("*"),           "")) %>% 
  mutate(end_station_name   = str_replace_all(end_station_name,   fixed(" - Charging"), "")) %>% 
  mutate(end_station_name   = str_replace_all(end_station_name,   fixed(" (Temp)"),     "")) %>% 
  mutate(end_station_name   = str_replace_all(end_station_name,   fixed("amp;"),        ""))
```

## Identifying and Correcting Missing Values

```{r}
# Count the total missing number each column
colSums(is.na(trip_data_v2))
```

```{r}
# Fill in the missing values in starting station based on latitude and longitude
trip_data_v2 <- trip_data_v2 %>% 
    group_by(start_lat, start_lng) %>% 
    fill(start_station_name, .direction = "downup") %>% 
    ungroup()

# Fill in the missing values in ending station based on latitude and longitude
trip_data_v2 <- trip_data_v2 %>% 
    group_by(end_lat, end_lng) %>% 
    fill(end_station_name, .direction = "downup") %>% 
    ungroup()
```

```{r}
# Remove all rows that have any missing values
trip_data_v2 <- trip_data_v2[complete.cases(trip_data_v2), ]
```

```{r}
# Let's check the starting and ending station names again
start_station_v2 <- count(trip_data_v2, start_station_name)
end_station_v2 <- count(trip_data_v2, end_station_name)
```

```{r}
# Check to make sure there is no missing values each column
colSums(is.na(trip_data_v2))
```

## Adding new calculated columns

## Removing outlier values

# Data Analysis

## Visualizations

## Key Findings

-   
-   
-   
-   
-   

# Conclusion

# Recommendations

-   
-   
-   

------------------------------------------------------------------------
